######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 22 03:24:46 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
ICON = cartulina.icns
# Input
HEADERS += cartulinaabout.h cartulinamain.h deckparser.h ui_about.h
FORMS += ui_about.ui ui_cartulinamain.ui
SOURCES += cartulinaabout.cpp cartulinamain.cpp deckparser.cpp main.cpp
